version: "3.4"

services:
  web:
    build:
      context: .
      args:
        - MOODLE_VERSION=MOODLE_403_STABLE
        - MOODLE_CODECHECKER_VERSION=v3.0.2
        - MOODLE_PLUGIN_RELATIVE_PATH=local/greetings
    ports:
      - 8080:80
    environment:
      MOODLE_DOCKER_DBHOST: db
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: secret
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: "moodle.veri.local"
      MOODLE_DOCKER_WEB_PORT: 8080
    volumes:
      - .:/usr/local/src
    depends_on:
      - db

  db:
    image: mysql:8.4
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: secret
